/**
 * Question bank for the Unhinged Text Game
 *
 * 200+ weird, opinionated, funny, short questions organized by category.
 * Designed to spark dumb arguments between two friends.
 */

export interface Question {
  text: string;
  category: string;
}

export const QUESTIONS: Question[] = [
  // ── Animals ──────────────────────────────────────────────
  { text: "What's the rudest animal?", category: "animals" },
  { text: "Which animal would ghost you?", category: "animals" },
  { text: "Which animal acts like it pays rent?", category: "animals" },
  { text: "Which animal would be the worst texter?", category: "animals" },
  { text: "Which animal would interrupt you mid-sentence?", category: "animals" },
  { text: "Which animal is secretly judging you?", category: "animals" },
  { text: "Which animal would start drama in a group chat?", category: "animals" },
  { text: "Which animal would fake being deep?", category: "animals" },
  { text: "Which animal would say 'you've changed' after 2 weeks?", category: "animals" },
  { text: "Which animal would read your diary out loud?", category: "animals" },
  { text: "Which animal gives unsolicited advice?", category: "animals" },
  { text: "Which animal would unfollow you first?", category: "animals" },
  { text: "Which animal has the most toxic ex energy?", category: "animals" },
  { text: "Which animal thinks it's funnier than it is?", category: "animals" },
  { text: "Which animal would leave you on read?", category: "animals" },
  { text: "Which animal has main character syndrome?", category: "animals" },
  { text: "Which animal would steal your fries?", category: "animals" },
  { text: "Which animal would show up uninvited?", category: "animals" },
  { text: "Which animal acts tough but cries in private?", category: "animals" },
  { text: "Which animal would spoil the movie ending?", category: "animals" },
  { text: "Which animal would eat your leftovers without asking?", category: "animals" },
  { text: "Which animal would screenshot your texts?", category: "animals" },
  { text: "Which animal would double-dip?", category: "animals" },
  { text: "Which animal would bring a guitar to a party?", category: "animals" },
  { text: "Which animal peaked in high school?", category: "animals" },

  // ── Objects ──────────────────────────────────────────────
  { text: "What object has the worst vibes?", category: "objects" },
  { text: "What object would betray you for $5?", category: "objects" },
  { text: "What's the most dramatic household item?", category: "objects" },
  { text: "What object is secretly manipulative?", category: "objects" },
  { text: "What object acts like the main character?", category: "objects" },
  { text: "What object would gaslight you?", category: "objects" },
  { text: "What object has the biggest god complex?", category: "objects" },
  { text: "What object would throw you under the bus?", category: "objects" },
  { text: "What object would talk behind your back?", category: "objects" },
  { text: "What object gives off serial killer vibes?", category: "objects" },
  { text: "What object in your house secretly hates you?", category: "objects" },
  { text: "What object would win a passive-aggressive award?", category: "objects" },
  { text: "What object tries too hard to be useful?", category: "objects" },
  { text: "What object has unearned confidence?", category: "objects" },
  { text: "What object would sell your secrets?", category: "objects" },
  { text: "What object is the Karen of household items?", category: "objects" },
  { text: "What object would file a noise complaint?", category: "objects" },
  { text: "What object would send a passive-aggressive email?", category: "objects" },

  // ── Food ─────────────────────────────────────────────────
  { text: "What fruit has the most attitude?", category: "food" },
  { text: "What's the least trustworthy vegetable?", category: "food" },
  { text: "Which snack has the biggest ego?", category: "food" },
  { text: "What food feels passive-aggressive?", category: "food" },
  { text: "What food is lying about being healthy?", category: "food" },
  { text: "What food would cheat on you?", category: "food" },
  { text: "What food thinks it's better than it is?", category: "food" },
  { text: "What food has the worst personality?", category: "food" },
  { text: "What food would post inspirational quotes?", category: "food" },
  { text: "What food would be a terrible roommate?", category: "food" },
  { text: "What condiment has the biggest attitude?", category: "food" },
  { text: "What food is secretly toxic?", category: "food" },
  { text: "What food would be a terrible therapist?", category: "food" },
  { text: "What drink has the most unearned confidence?", category: "food" },
  { text: "What food would start a pyramid scheme?", category: "food" },
  { text: "What food thinks it's a personality trait?", category: "food" },
  { text: "What's the most suspicious cheese?", category: "food" },
  { text: "What food would vague-post about you?", category: "food" },
  { text: "What cereal brand has the biggest ego?", category: "food" },
  { text: "What fast food item acts like it's gourmet?", category: "food" },

  // ── Colors ───────────────────────────────────────────────
  { text: "What color is the most arrogant?", category: "colors" },
  { text: "What color is fake nice?", category: "colors" },
  { text: "What color is judging you?", category: "colors" },
  { text: "What color has the worst vibes at 3 AM?", category: "colors" },
  { text: "What color would snitch on you?", category: "colors" },
  { text: "What color has a god complex?", category: "colors" },
  { text: "What color is trying too hard?", category: "colors" },
  { text: "What color would lie on its resume?", category: "colors" },
  { text: "What color is the most passive-aggressive?", category: "colors" },
  { text: "What color thinks it's everyone's favorite?", category: "colors" },
  { text: "What color would ghost you after one date?", category: "colors" },
  { text: "What color peaked in the '90s?", category: "colors" },

  // ── Weather ──────────────────────────────────────────────
  { text: "What's the most passive-aggressive weather?", category: "weather" },
  { text: "What weather feels like a personal attack?", category: "weather" },
  { text: "What weather is the most manipulative?", category: "weather" },
  { text: "What weather would cancel plans last minute?", category: "weather" },
  { text: "What weather has the most chaotic energy?", category: "weather" },
  { text: "What weather would ruin your wedding on purpose?", category: "weather" },
  { text: "What weather is lying about its intentions?", category: "weather" },
  { text: "What weather would subtly insult your outfit?", category: "weather" },
  { text: "What weather would send you a 'we need to talk' text?", category: "weather" },
  { text: "What weather thinks it's everyone's favorite?", category: "weather" },

  // ── Abstract ─────────────────────────────────────────────
  { text: "What's the most judgmental shape?", category: "abstract" },
  { text: "Which number feels fake?", category: "abstract" },
  { text: "What font is the most condescending?", category: "abstract" },
  { text: "What day of the week has the worst energy?", category: "abstract" },
  { text: "What month is the most sus?", category: "abstract" },
  { text: "What letter of the alphabet is two-faced?", category: "abstract" },
  { text: "What emoji is secretly mean?", category: "abstract" },
  { text: "What time of day has the worst vibes?", category: "abstract" },
  { text: "What math concept is the most dramatic?", category: "abstract" },
  { text: "What punctuation mark has the biggest ego?", category: "abstract" },
  { text: "What shape would start a cult?", category: "abstract" },
  { text: "What number would lie to your face?", category: "abstract" },
  { text: "What font would commit a crime?", category: "abstract" },
  { text: "What keyboard shortcut has the most power?", category: "abstract" },
  { text: "What unit of measurement is lying about its importance?", category: "abstract" },

  // ── Debate ───────────────────────────────────────────────
  { text: "Is cereal a soup or a lifestyle?", category: "debate" },
  { text: "Is a hotdog a sandwich or a personality trait?", category: "debate" },
  { text: "If ghosts wear clothes, are those ghost clothes?", category: "debate" },
  { text: "If a mirror lies, how would you know?", category: "debate" },
  { text: "Are eyebrows facial hair or something else entirely?", category: "debate" },
  { text: "Is water wet or just a liar?", category: "debate" },
  { text: "Do fish know they're wet?", category: "debate" },
  { text: "Is a quesadilla a sandwich?", category: "debate" },
  { text: "Is a straw one hole or two?", category: "debate" },
  { text: "Would you rather fight 100 duck-sized horses or 1 horse-sized duck?", category: "debate" },
  { text: "If you punch yourself and it hurts, are you strong or weak?", category: "debate" },
  { text: "Is the S or C silent in 'scent'?", category: "debate" },
  { text: "Is a Pop-Tart a ravioli?", category: "debate" },
  { text: "If two mind readers read each other's minds, whose mind are they reading?", category: "debate" },
  { text: "Is ketchup a smoothie?", category: "debate" },
  { text: "Is a thumb a finger?", category: "debate" },
  { text: "Would a fly without wings be called a walk?", category: "debate" },
  { text: "Is a calzone just a pizza folder?", category: "debate" },

  // ── Vibes ────────────────────────────────────────────────
  { text: "What normal thing has terrible vibes?", category: "vibes" },
  { text: "What harmless thing annoys you too much?", category: "vibes" },
  { text: "What instantly breaks the vibe?", category: "vibes" },
  { text: "What's an ick that shouldn't be an ick?", category: "vibes" },
  { text: "What gives off 'I peaked in high school' energy?", category: "vibes" },
  { text: "What screams 'I have no hobbies'?", category: "vibes" },
  { text: "What's the biggest red flag in someone's apartment?", category: "vibes" },
  { text: "What's weirdly attractive for no reason?", category: "vibes" },
  { text: "What hobby is a secret cry for help?", category: "vibes" },
  { text: "What's the most unhinged thing to do at a grocery store?", category: "vibes" },
  { text: "What's a green flag that's actually a red flag?", category: "vibes" },
  { text: "What's the most chaotic thing in your kitchen?", category: "vibes" },
  { text: "What's the most suspicious compliment?", category: "vibes" },
  { text: "What screams 'I'm the main character'?", category: "vibes" },
  { text: "What gives off 'reply-all to company email' energy?", category: "vibes" },

  // ── People / Social ──────────────────────────────────────
  { text: "What's the most unhinged thing you can do at brunch?", category: "social" },
  { text: "What's the most chaotic first date idea?", category: "social" },
  { text: "What's the worst song to play at a funeral?", category: "social" },
  { text: "What's the most aggressive compliment?", category: "social" },
  { text: "What's the worst thing to whisper to someone?", category: "social" },
  { text: "What's the most threatening thing you can say with a smile?", category: "social" },
  { text: "What's the worst way to start a conversation?", category: "social" },
  { text: "What's the most suspicious thing to say on an elevator?", category: "social" },
  { text: "What's the worst thing to be caught doing at work?", category: "social" },
  { text: "What's the most unhinged LinkedIn post you can imagine?", category: "social" },
  { text: "What's the worst bio for a dating app?", category: "social" },
  { text: "What's the most chaotic potluck dish?", category: "social" },
  { text: "What's the worst thing to yell in a library?", category: "social" },
  { text: "What's the most unhinged thing to put on a business card?", category: "social" },
  { text: "What's the worst wedding toast ever?", category: "social" },

  // ── Hypotheticals ────────────────────────────────────────
  { text: "If your life had a theme song, what genre would it be?", category: "hypothetical" },
  { text: "If you were a font, which one would you be?", category: "hypothetical" },
  { text: "If you were a kitchen appliance, which one?", category: "hypothetical" },
  { text: "If your personality was a weather pattern, what would it be?", category: "hypothetical" },
  { text: "If you had to be haunted by one celebrity ghost, who?", category: "hypothetical" },
  { text: "If your last text was your campaign slogan, are you winning?", category: "hypothetical" },
  { text: "If you were a candle scent, what would it be?", category: "hypothetical" },
  { text: "If your life was a Netflix genre, what category?", category: "hypothetical" },
  { text: "If you could only eat one condiment forever, which one?", category: "hypothetical" },
  { text: "If you had to pick an animal to be your lawyer, which one?", category: "hypothetical" },
  { text: "If your anxiety was a person, what would they look like?", category: "hypothetical" },
  { text: "If you were a type of pasta, which one?", category: "hypothetical" },
  { text: "If your life had a Yelp review, how many stars?", category: "hypothetical" },
  { text: "If you were a board game, which one?", category: "hypothetical" },
  { text: "If your browser history was a movie, what's the rating?", category: "hypothetical" },

  // ── Conspiracy / Weird ───────────────────────────────────
  { text: "What common object is definitely hiding something?", category: "conspiracy" },
  { text: "What animal is 100% a government drone?", category: "conspiracy" },
  { text: "What food was definitely invented by accident?", category: "conspiracy" },
  { text: "What's something everyone pretends to understand?", category: "conspiracy" },
  { text: "What's something we all silently agree to ignore?", category: "conspiracy" },
  { text: "What's the most suspicious room in any house?", category: "conspiracy" },
  { text: "What's something that feels illegal but isn't?", category: "conspiracy" },
  { text: "What's something that's technically legal but feels wrong?", category: "conspiracy" },
  { text: "What everyday activity would look insane to aliens?", category: "conspiracy" },
  { text: "What's the most suspicious aisle in a grocery store?", category: "conspiracy" },
  { text: "What appliance is secretly plotting against you?", category: "conspiracy" },
  { text: "What children's show is actually terrifying?", category: "conspiracy" },

  // ── Ranking / Hot Takes ──────────────────────────────────
  { text: "What's the most overrated thing in existence?", category: "hot-takes" },
  { text: "What's the most underrated thing that deserves hype?", category: "hot-takes" },
  { text: "What's the most pointless invention ever?", category: "hot-takes" },
  { text: "What's the most overrated social media platform?", category: "hot-takes" },
  { text: "What's the worst pizza topping? Fight me.", category: "hot-takes" },
  { text: "What movie is a 10/10 that nobody talks about?", category: "hot-takes" },
  { text: "What song is objectively terrible but you secretly love?", category: "hot-takes" },
  { text: "What's the most overhyped holiday?", category: "hot-takes" },
  { text: "What's the worst trend that people need to let go of?", category: "hot-takes" },
  { text: "What's the most overrated city?", category: "hot-takes" },
  { text: "What's a hill you'd die on that nobody agrees with?", category: "hot-takes" },
  { text: "What's the worst app on your phone?", category: "hot-takes" },
  { text: "What's the most pointless school subject?", category: "hot-takes" },
  { text: "What's the most toxic fandom?", category: "hot-takes" },
  { text: "What's the worst flavor of ice cream?", category: "hot-takes" },

  // ── Chaos ────────────────────────────────────────────────
  { text: "What would be the worst superpower?", category: "chaos" },
  { text: "What would you rename the moon?", category: "chaos" },
  { text: "If animals could talk, which one would be the rudest?", category: "chaos" },
  { text: "What would be the worst thing to hear from your dentist?", category: "chaos" },
  { text: "What would be the worst flavor of chips?", category: "chaos" },
  { text: "What would be the worst name for a band?", category: "chaos" },
  { text: "What would be the worst catchphrase?", category: "chaos" },
  { text: "What would be the worst thing to automate?", category: "chaos" },
  { text: "What would be the worst theme for a party?", category: "chaos" },
  { text: "What would be the worst thing to find in your pocket?", category: "chaos" },
  { text: "If you had to live in one store forever, which one?", category: "chaos" },
  { text: "What would be the worst alarm sound?", category: "chaos" },
  { text: "What would be the worst thing to be famous for?", category: "chaos" },
  { text: "If you had to eat one meal forever, what would it be?", category: "chaos" },
  { text: "What would be the worst way to introduce yourself?", category: "chaos" },
];
