'use client';

import { useState } from 'react';
import dynamic from 'next/dynamic';
import { CRESection } from '@/components/creait/ui';
import { CRECard } from '@/components/creait/ui';
import {
  H2,
  H3,
  BodyLG,
  BodyMD,
  LabelSM,
} from '@/components/creait/typography';
import { CRE_COLORS } from '@/lib/creait/design-tokens/colors';

// Lazy load demo components for code splitting
const LoadingDemo = () => (
  <div className="flex items-center justify-center py-12">
    <div className="text-center">
      <div className="animate-pulse mb-4">
        <div className="w-12 h-12 border-4 border-terminal-gold/30 border-t-terminal-gold rounded-full animate-spin mx-auto" />
      </div>
      <p className="text-terminal-gold font-mono text-sm">Loading demo...</p>
    </div>
  </div>
);

const OpportunityDashboardDemo = dynamic(
  () => import('@/components/creait/demos/OpportunityDashboardDemo'),
  { loading: () => <LoadingDemo />, ssr: false }
);

const ScoreBreakdownDemo = dynamic(
  () => import('@/components/creait/demos/ScoreBreakdownDemo'),
  { loading: () => <LoadingDemo />, ssr: false }
);

const EmailDraftsDemo = dynamic(
  () => import('@/components/creait/demos/EmailDraftsDemo'),
  { loading: () => <LoadingDemo />, ssr: false }
);

type DemoTab = 'dashboard' | 'scoring' | 'emails';

/**
 * Slide 3: Live Demo - Interactive CREaiT Platform Demos
 *
 * Shows 3 interactive demos:
 * 1. Opportunity Dashboard (table with sorting/filtering)
 * 2. Score Breakdown (charts and explanations)
 * 3. AI Email Drafts (tone variants)
 */
export default function DemoSlidePage() {
  const [activeTab, setActiveTab] = useState<DemoTab>('dashboard');

  const tabs = [
    {
      id: 'dashboard' as DemoTab,
      label: 'Opportunity Dashboard',
      icon: '',
      color: CRE_COLORS.primary,
    },
    {
      id: 'scoring' as DemoTab,
      label: 'Score Breakdown',
      icon: '',
      color: CRE_COLORS.secondary,
    },
    {
      id: 'emails' as DemoTab,
      label: 'AI Email Drafts',
      icon: '️',
      color: CRE_COLORS.accent,
    },
  ];

  return ( <CRESection
      title="Live Demo"
      subtitle="Explore CREaiT's core features with interactive demos"
      variant="demo"
    > {/* Demo Introduction */} <CRECard variant="accent" size="large" className="mb-8 text-center"> <H2 className="mb-4">Interactive Platform Demo</H2> <BodyLG color={CRE_COLORS.text.secondary} className="max-w-3xl mx-auto"> Experience CREaiT as if you were a broker. Click through the tabs below to see daily
          prioritization, transparent AI scoring, and context-aware email generation. </BodyLG> </CRECard> {/* Tab Navigation */} <div className="mb-8"> <div className="flex gap-3 p-2 rounded-xl bg-white/5 border border-white/10"> {tabs.map((tab) => ( <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex-1 px-6 py-4 rounded-lg font-medium transition-all flex items-center justify-center gap-3 ${
                activeTab === tab.id
                  ? 'shadow-lg'
                  : 'hover:bg-white/5'
              }`}
              style={{
                backgroundColor:
                  activeTab === tab.id ? `${tab.color}20` : 'transparent',
                color: activeTab === tab.id ? tab.color : 'rgba(255, 255, 255, 0.6)',
              }}
            > <span className="text-2xl">{tab.icon}</span> <span>{tab.label}</span> </button> ))} </div> </div> {/* Demo Content */} <CRECard variant="neutral" size="large"> <div className="min-h-[600px]"> {activeTab === 'dashboard' && <OpportunityDashboardDemo />}
          {activeTab === 'scoring' && <ScoreBreakdownDemo />}
          {activeTab === 'emails' && <EmailDraftsDemo />} </div> </CRECard> {/* Demo Notes */} <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-8"> <CRECard variant="primary"> <div className="flex items-start gap-3"> <span className="text-3xl"></span> <div> <H3 className="mb-2 text-lg">Real Data</H3> <BodyMD color={CRE_COLORS.text.secondary}> All examples use anonymized data from actual pilot customer pipelines </BodyMD> </div> </div> </CRECard> <CRECard variant="secondary"> <div className="flex items-start gap-3"> <span className="text-3xl"></span> <div> <H3 className="mb-2 text-lg">Fully Interactive</H3> <BodyMD color={CRE_COLORS.text.secondary}> Sort, filter, and explore the interface exactly as brokers would </BodyMD> </div> </div> </CRECard> <CRECard variant="accent"> <div className="flex items-start gap-3"> <span className="text-3xl"></span> <div> <H3 className="mb-2 text-lg">AI-Powered</H3> <BodyMD color={CRE_COLORS.text.secondary}> Scores and emails generated by Anthropic Claude with CRE-specific context </BodyMD> </div> </div> </CRECard> </div> </CRESection> );
}
