version: 2
snapshot:
  widths:
    - 375   # Mobile
    - 768   # Tablet
    - 1280  # Desktop
  min-height: 1024
  enable-javascript: true
  percy-css: |
    /* Hide dynamic elements */
    [data-dynamic="true"] { visibility: hidden !important; }
    .animate-pulse { animation: none !important; }
